project:
  type: website
  output-dir: docs
website:

  open-graph: true
  title: "Christine Papas"
  navbar:
    search: False
    right:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/papaschristine8828/
      - icon: github
        href: https://github.com/s-Yk88



format:
  html:
    theme:
      - sandstone
      - custom.scss
    css: styles.css
    toc: false
    


